---
title: "Variant Model"
author: "Amy Hurford"
date: "13/04/2022"
output: 
  html_document: 
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, message = FALSE, warning=FALSE, include=FALSE}
library(tidyr)
library(dplyr)
library(McMasterPandemic)
library(ggplot2)
library(lubridate)
library(patchwork)
setwd("/Users/ahurford/Desktop/Work/Research/Research_Projects/2022/nfld-macpan")
source('get_data.R')
source('functions.R')
fit = readRDS('fit.rds')
fitted_data = readRDS('fitted_data.rds')
observed_data = readRDS('observed_data.rds')

params = read_params("PHAC.csv")
params["N"] = 522453  # nfld population
params = fix_pars(params)

end_date = max(observed_data$date)+14
#Changing from 90 to 15 improves fit substantially
start_date_offset = 15
start_date = min(observed_data$date) - start_date_offset
L = length(seq(as.Date(start_date),as.Date(end_date),by="days"))
L1 = length(seq(as.Date(start_date), as.Date("2022-01-04")))
L2 = length(seq(as.Date(start_date), as.Date("2022-02-17")))

params_timevar = data.frame(
  Date = seq(as.Date(start_date),as.Date(end_date),by="days"), # dates of breakpoints
  Symbol = "beta0",                     # parameters to vary
  Value = rep(0, L),                   
  Type = "abs"                          # abs = change to value in Value col
)

state <- make_state(params=params)
res1 <- run_sim(params=params,params_timevar=params_timevar,state=state, start_date=start_date, end_date=end_date)
scenario = data.frame(date=res1$date,H=res1$H, D = res1$death, report = res1$report)
```


# Variant fraction

```{r}
var.frac <- function(dates){
  # 35-40% samples were BA.2 on April 1.
  # Assume a 7 day lag.
  # This paramterization gives 35% on March 25. 
  t0="2022-02-10"
  i = which(dates==t0)
  L = length(dates)
  p = rep(0,length(dates))
  p0 = 0.01
  s = 0.09
  t = seq(1,length(seq(i:L)))
  p[i:L] = exp(s*t)*p0/(1-p0+exp(s*t)*p0)
  var.frac = data.frame(dates=dates, var.frac = p)
  return(var.frac)
} 
```

```{r}
cases = filter(observed_data,var=="report")
fitted_cases = filter(fitted_data,var=="report")
p = var.frac(fitted_cases$date)$var.frac
output = data.frame(date = fitted_cases$date, cases=fitted_cases$value, BA.2 = p*fitted_cases$value)

g.var = ggplot()+
  geom_line(data=cases,aes(x= as.Date(date),y=value), col = "blue", lwd=0.2)+
  geom_point(data=cases,aes(x= as.Date(date),y=value), col = "blue", pch=21, fill = "white")+
geom_ribbon(data= output, aes(x= as.Date(date), ymax = cases,ymin=0),fill = "darkblue", alpha = 0.3)+
geom_ribbon(data= output, aes(x= as.Date(date), ymax = BA.2,ymin=0),fill = "blue", alpha = 0.3)+
  annotate("text", x = as.Date("2022-03-08"), y = 200, label = "BA.1", col = "blue")+
    annotate("text", x = as.Date("2022-03-28"), y = 100, label = "BA.2", col="darkblue")+
  ylab("Reported new cases")+ scale_x_date(date_breaks = "7 day", date_labels = "%d %b", limits = c(as.Date("2021-12-01"), tail(as.Date(output$date),1)))+
  theme(axis.text.x = element_text(angle = 90),legend.position = "none")+xlab("")

```

